# fly.toml app configuration file generated for jonah-phonebook on 2024-06-11T21:03:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jonah-phonebook'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
